# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/fuent/.Xilinx/ECE520L/Sandbox/digital_lock_soc_rf/digital_lock_soc_rf.srcs/sources_1/bd/digital_lock_bd_rf/ip/digital_lock_bd_rf_processing_system7_0_1/digital_lock_bd_rf_processing_system7_0_1.xci
# IP: The module: 'digital_lock_bd_rf_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fuent/.Xilinx/ECE520L/Sandbox/digital_lock_soc_rf/digital_lock_soc_rf.gen/sources_1/bd/digital_lock_bd_rf/ip/digital_lock_bd_rf_processing_system7_0_1/digital_lock_bd_rf_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'digital_lock_bd_rf_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/fuent/.Xilinx/ECE520L/Sandbox/digital_lock_soc_rf/digital_lock_soc_rf.srcs/sources_1/bd/digital_lock_bd_rf/ip/digital_lock_bd_rf_processing_system7_0_1/digital_lock_bd_rf_processing_system7_0_1.xci
# IP: The module: 'digital_lock_bd_rf_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fuent/.Xilinx/ECE520L/Sandbox/digital_lock_soc_rf/digital_lock_soc_rf.gen/sources_1/bd/digital_lock_bd_rf/ip/digital_lock_bd_rf_processing_system7_0_1/digital_lock_bd_rf_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'digital_lock_bd_rf_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
