# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/digital_lock.xdc

# Block Designs: bd/digital_lock_bd_rf/digital_lock_bd_rf.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==digital_lock_bd_rf || ORIG_REF_NAME==digital_lock_bd_rf} -quiet] -quiet

# IP: bd/digital_lock_bd_rf/ip/digital_lock_bd_rf_processing_system7_0_1/digital_lock_bd_rf_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==digital_lock_bd_rf_processing_system7_0_1 || ORIG_REF_NAME==digital_lock_bd_rf_processing_system7_0_1} -quiet] -quiet

# IP: bd/digital_lock_bd_rf/ip/digital_lock_bd_rf_digital_lock_0_0/digital_lock_bd_rf_digital_lock_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==digital_lock_bd_rf_digital_lock_0_0 || ORIG_REF_NAME==digital_lock_bd_rf_digital_lock_0_0} -quiet] -quiet

# IP: bd/digital_lock_bd_rf/ip/digital_lock_bd_rf_ps7_0_axi_periph_0/digital_lock_bd_rf_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==digital_lock_bd_rf_ps7_0_axi_periph_0 || ORIG_REF_NAME==digital_lock_bd_rf_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/digital_lock_bd_rf/ip/digital_lock_bd_rf_rst_ps7_0_50M_0/digital_lock_bd_rf_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==digital_lock_bd_rf_rst_ps7_0_50M_0 || ORIG_REF_NAME==digital_lock_bd_rf_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/digital_lock_bd_rf/ip/digital_lock_bd_rf_auto_pc_0/digital_lock_bd_rf_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==digital_lock_bd_rf_auto_pc_0 || ORIG_REF_NAME==digital_lock_bd_rf_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/fuent/.Xilinx/ECE520L/Sandbox/digital_lock_soc_rf/digital_lock_soc_rf.gen/sources_1/bd/digital_lock_bd_rf/digital_lock_bd_rf_ooc.xdc
